# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Comment this line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!
target 'YLDouYuZB' do

pod 'Alamofire', '~> 4.0.0'
pod 'Kingfisher', '~> 3.1.0'
end
