# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Comment this line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!
target 'YLDouYuZB' do

pod 'Alamofire'
pod 'Kingfisher','~>2.4.0'
end
